# This file is a GitLab CI/CD configuration file
# You can override the included template(s) by including variable overrides

stages:
  - test
  - build

# Include the SAST template
include:
  - template: Security/SAST.gitlab-ci.yml

# Job for SAST
sast:
  stage: test

# Job to set up the Node.js environment and run the application
node_app:
  stage: build
  image: node:14 # You can specify a different Node.js version if needed
  script:
    - echo "Cloning the project..."
    - git clone https://github.com/devenes/node-js-dummy-test
    - cd node-js-dummy-test
    - echo "Installing dependencies..."
    - npm install
    - echo "Starting the application..."
    - npm start &
    - echo "Application is running at http://localhost:3000"
    - sleep 10 # Wait a bit to ensure the server is up before running tests
    # Here you can add commands to run your tests, e.g., npm test
  only:
    - main # Adjust this to the branch you want to run the pipeline on
